#!/usr/bin/env ruby
require 'json'
require 'socket'

sock = TCPSocket.new(ARGV[0], ARGV[1].to_i)

serf_env = Hash[ENV.select{|k,v|/SERF/ =~ k}]
input = $stdin.read

sock.puts({env: serf_env, input: input}.to_json)
sock.close_write

if ENV["SERF_EVENT"] == "query"
  $stdout.write sock.read
end
