language: ruby
cache: bundler
rvm:
  - "2.1.1"
  - "2.0.0"
  - "2.1.0"
  - "ruby-head"

matrix:
  allow_failures:
    - rvm:
      - "2.1.0"
      - "ruby-head"
  fast_finish: true
notifications:
  email:
    - travis-ci@sorah.jp
before_script:
  - ruby extconf.rb
  - mkdir -p vendor/serf
  - curl -L -o vendor/serf/serf.zip https://dl.bintray.com/mitchellh/serf/0.6.0_linux_amd64.zip
  - unzip -d vendor/serf vendor/serf/serf.zip
  - export PATH=$PWD/vendor/serf:$PATH
script: bundle exec rspec -fd ./spec
